// <auto-generated />
namespace Estoque.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Usuarios_create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Usuarios_create));
        
        string IMigrationMetadata.Id
        {
            get { return "202604292158137_Usuarios_create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
